import type { Metadata } from "next";
import "./globals.css";
import DesktopNav from "@/components/navigation/DesktopNav";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import Footer from "@/components/Main/Footer";
import MobileNav from "@/components/navigation/MobileNav";

const Monte = Open_Sans({ subsets: ["latin"] });
const brush = localFont({
  src: "../fonts/FontMesa - Regular.otf",
  variable: "--brush",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Monte.className} ${brush.variable}`}>
        <div>
          <DesktopNav />
          <MobileNav />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
